###################
## MEDIUM TEMPLATE #
###################
###################
## COMMON PARAMS ##
###################
##################################
####    INVENTORY PARAMS      ####
##################################

HELM_NODE="localhost"
CLUSTER_NAME="PROJECT_CLUSTER"
#should be true
IS_HELM_NODE_MASTERNODE="true" 

## Location where Helm charts will be checked out on the tools jump box
# location on HELM NODE, ansible user should be able to read/write
#HELM_CHECKOUT_LOCATION="/jenkinsnfs/HELM_CHARTS"
HELM_CHECKOUT_LOCATION="GIT_USER_HOME_DIR/HELM_CHARTS"

#Kubernetes secret name used to pull images from docker registry
#Use lower case alphanumeric characters and a hyphen (-) in the secret. The secret must start and end with an alphanumeric character. For example, image-1.
#In case of manual input file method, create this secret manually using the below command
#kubectl create secret docker-registry <secret_name> --docker-server=<ex:containers.bmc.com> --docker-username=<ex:AWS> --docker-password='<password token>' -n <cluster namespace>
#In Uber pipeline input parameter "IMAGESECRET_NAME" refers to this parameter.
IMAGEPULLSECRETS_NAME=""

# Max Timeout, in seconds, for checking any pod. Default 5 hours
POD_CHECKER_TIMEOUT=300

### Pipeline Controllers ### according to test scenarios we can enable or disable the components
PLATFORM="HELIX_REMEDY" # ITSM, SRM, SLM flag
MIDTIER="HELIX_REMEDY"  # Front end for ARSystem, needed to run automated scripts
SMARTIT="HELIX_REMEDY"  # needed
SMARTREPORTING="false" # needed
TSOMPLUGIN="false"     # needed - ?
ATRIUMWEBSERVICE="true" # needed - ?
VIRTUALCHATPLUGIN="HELIX_VIRTUALCHAT" # needed - ?
VIRTUALCHATSERVER="HELIX_VIRTUALCHAT"

### UID For Generating Spcial License ###
LICENSE_UID="USER_APPLYING_LICENSE"

# Cops does not have values for below. Hence, default value is "false".
SCCM="false"
BCM="false"
OPENFIRE="HELIX_OPENFIRE"
DRIFTMANAGEMENTPLUGIN="false"							 
PCIPLUGIN="false"

##Database Restore Controllers(true/false)###
AR_DB_RESTORE="true"
SMARTREPORTING_DB_RESTORE="false"
#SMARTIT_DB_RESTORE="true"

### Other Controllers ###
DISABLE_EXTERNAL_MIDTIERCACHEBUILDER="false"
LOCALES="false"
CONFIGURE_STORAGE="true"
GRAFANA="false"
PROMETHEUS="false"
LOGS_UPLOAD_FTP="FALSE"
PLATFORM_INT_PARALLELDEPLOYMENT_ENABLED="false"
PLATFORM_SR_PARALLELDEPLOYMENT_ENABLED="false"
CUSTOMER_COMPANY_NAME="CUSTOMER_NAME_INPUT"
ENABLE_PSR_TESTS="false"	

MIDTIER_URL_PORT="443"
MIDTIER_URL_PROTOCOL="https"
RSSO_EXTERNAL_URL_CALCULATED=""
RSSO_SERVICE_URL_CALCULATED=""
MIDTIER_UPDATED_CONFIGMAP_PREFETCHXML=""
SMARTREPORTING_DATA_SOURCE_REFRESH_INTERVAL="15"
#MIDTIER_INT_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-int.${CLUSTER_DOMAIN}" #Replace the variables with actual values bmc.com
#MIDTIER_USER_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}.${CLUSTER_DOMAIN}"
MIDTIER_INT_URL=""
MIDTIER_USER_URL=""

RECON_REPORT_UTILITY_URL=""
DDM_EXTRACT_TOOL_URL=""
DDM_MIGRATE_TOOL_URL=""

#JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.262.b10-0.el7_8.x86_64/jre" # Java home set on Ansible server
JAVA_HOME="${JAVA_HOMEPATH}"
AUTORECON="FALSE"
AUTORECON_RECONCILE_VUIS="false"								
OPENFIRE_DB_TYPE="postgres"

## Admin details to connect to Postgres Database Server and create users and databases ##
DB_ADMIN_USER="DATABASE_ADMIN_USER"
#In Uber pipeline, input parameter, "DATABASE_ADMIN_PASSWORD" refers to this parameter.
DB_ADMIN_PASSWORD=""
DB_USE_BMC_APIS=""

##### WARNING: To be filled only in case of explicit failure of platform_db_upgrade container(QA Only)(Any one argument) #####
AR_INSTALLER_VM_ARGUMENTS=""
ATRIUM_INSTALLER_VM_ARGUMENTS=""
AI_INSTALLER_VM_ARGUMENTS=""

#####################
#### PCIPLUGIN ####
#####################

PCIPLUGIN_REPLICA_COUNT="1"
PCIPLUGIN_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PCIPLUGIN_JAVA_MIN_HEAP_SIZE="-Xms256m"

## RESOURCES ##
PCIPLUGIN_MEMORY_REQUEST="0.5Gi"
PCIPLUGIN_CPU_REQUEST="1"
PCIPLUGIN_MEMORY_LIMIT="1Gi"
PCIPLUGIN_CPU_LIMIT="2"

## volumeMounts ##
PCIPLUGIN_VOLUME_MOUNT_ENABLED="true"

## volumes ##
PCIPLUGIN_VOLUME_ENABLED="true"

## Openfire ##
OPENFIRE_XMPP_DOMAIN="openfire-ext"
###------------ PLATFORM DATABAsSE SERVICE PARAMETERS FOR SR(Aligned with COPS) ------------###
PLATFORM_SR_DB_USER=""
PLATFORM_SR_DB_PASSWORD=""
PLATFORM_SR_DB_HOSTNAME=""
PLATFORM_SR_DB_PORT=""
PLATFORM_SR_DB_JDBC_URL=''
####################################################################################################
###
# Set true to enable compact deployment
###
COMPACT_DEPLOYMENT_ENABLED="false"
# make true if you want to run test_suits
ENABLE_TEST_SUITE="false"

### HELM ###
#REPO URL to checkout Helm charts
HELM_REPO="http://zwl-gogs-1.onbmc.com:3000/core-remedy/containerization-certified.git"
HELM_REPO_SOURCE=""

###--------------------- VERSIONS ---------------------###
### (Corresponds to a tag or a branch in the HELM_REPO) ###

# Only required for Update/Upgrade. Leave empty in case of a fresh deployment
SOURCE_VERSION=""

HELM_VERSION="2022106.0.03.00"
TARGET_VERSION="2022106.0.03.00"

## File to be used for image tags
# Configurable only for DEV/QA. Default value should always be devops.yaml
IMAGES_FILE="dtr.yaml"

###--------------------- GLOBAL PARAMS/SETTINGS ---------------------###
PROJECT_TYPE="${ENVIRONMENT}"
# kubernetes Namespace where pods are deployed (kubectl -n $PROJECT_NAME)
#PROJECT_NAME="${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}"
PROJECT_NAME="${IS_NAMESPACE}"
CUSTOMER_SERVICE_NAME="${CUSTOMER_SERVICE_NAME}"
CUSTOMER_SERVICE_ALIAS="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}"
DOMAIN_NAME="${CLUSTER_DOMAIN}"
## IfNotPresent/Always
IMAGE_PULL_POLICY="IfNotPresent"

## Harbor Registry
#In Uber pipeline, input parameter, "HARBOR_REGISTRY_HOST" refers to this parameter.
REGISTRY="HARBOR_REGISTRY_HOST"
REGISTRY_ORG=""

RSSO_REGISTRY_PROJECT="bmc/lp00x"
#RSSO_REGISTRY_PROJECT="rsso/rsso"

IMAGE_REGISTRY_USERNAME='IMG_REGISTRY_USER'
IMAGE_REGISTRY_PASSWORD=

# Set to true to enable APPs upgrade in ZDT mode
#ENABLE_APPS_ZDT_UPGRADE="false"

# Set to false to enable licensing of the AR server using automation
DISABLE_LICENSING="true"

## true/false
ENABLE_JMX_MONITORING="true"
ENABLE_EPHEMERAL="false"

SERVICE_ANNOTATIONS=''

ROUTE_ENABLED="${route_enabled}"
ROUTE_TLS_ENABLED="${ROUTE_TLS_ENABLED}"
INGRESS_ENABLED="${ingress_enabled}"
INGRESS_CLASS="nginx"

# Provide value of FTS_ELASTICSEARCH_HOSTNAME parameter from uber pipeline. (Format can be elasticsearch-<ES_FTS_INSTANCE>-opendistro-es-data-svc)
ES_HOST="${FTS_ELASTICSEARCH_HOSTNAME}" 

SERVICE_TYPE_TCP="ClusterIP" # Loadbalancer, ClusterIP (need to check keyword/spelling)
SERVICE_TYPE_HTTP="ClusterIP" # Loadbalancer, ClusterIP (need to check)

RESTRICTED_SECURITY_CONTEXT_CONSTRAINTS_ENABLED="${OS_RESTRICTED_SCC}"
DB_JDBC_SSL_ENABLED="false"

# comma separated list of aliases with which to create extra ingress for midtier-int, midtier-user and smartit 
EXTRA_INGRESS_ALIASES="${EXTRA_PROJECT_SERVICE_NAME}"

# Custom Binary Path to pick binaries like helm/java/kubectl etc. from <USER-HOME-DIRECTORY>/bin
CUSTOM_BINARY_PATH="${CUSTOM_BINARY_PATH}"

###############
#### FLUENTBIT #####
###############
#FLUENTBIT_IMAGE_REGISTRY="$REGISTRY/onprem-infra/fluent-bit"
#FMETA_IMAGE_REGISTRY="$REGISTRY/onprem-infra/fmeta"
FLUENTBIT_IMAGE_REGISTRY="HARBOR_REGISTRY_HOST/bmc/lp00x"
FMETA_IMAGE_REGISTRY="HARBOR_REGISTRY_HOST/bmc/lp00x"
#Provide FLUENTBIT_ES_LOGS_HOSTNAME value as that of with, "<LOGS_ELASTICSEARCH_HOSTNAME>" from Uber pipeline.
FLUENTBIT_ES_LOGS_HOSTNAME="${LOGS_ELASTICSEARCH_HOSTNAME}"

###############
#### KIBANA #####
###############
#KIBANA_IMAGE_REGISTRY=bmc/lp00x
#KIBANA_IMAGE_REGISTRY_TAG=opendistro-for-elasticsearch-kibana-1.8.0

###############
#### ES #####
###############
ES_LOGS_PORT="${FLUENTBIT_LOGS_PORT}"
#ES_LOGS_INSTANCE="logs"
#ES_MASTER_REPLICAS="1"
#ES_MASTER_CPU_LIMIT="4"
#ES_MASTER_MEMORY_LIMIT="8192Mi"
#ES_MASTER_CPU_REQUEST="2"
#ES_MASTER_MEMORY_REQUEST="2048Mi"
##Specify the values in double quotes for MASTER_JAVA_OPTS
##Xms and Xmx should be always set to same value, Ex: MASTER_JAVA_OPTS="-Xms512m -Xmx512m"
#ES_MASTER_JAVA_OPTS="-Xms4G -Xmx4G"
#ES_DATA_REPLICAS="1"
#ES_DATA_CPU_LIMIT="8"
#ES_DATA_MEMORY_LIMIT="16384Mi"
#ES_DATA_CPU_REQUEST="4"
#ES_DATA_MEMORY_REQUEST="8192Mi"
#ES_DATA_JAVA_OPTS="-Xms8G -Xmx8G"
#ES_MASTER_STORAGE_SIZE="10Gi"
##In Uber pipeline, input parameter, "ES_LOGS_DATA_STORAGE_SIZE" refers to ES_DATA_STORAGE_SIZE.
#ES_DATA_STORAGE_SIZE="${ES_DATA_STORAGE_SIZE}Gi"
##In Uber pipeline, input parameter, "ELASTICSEARCH_LOG_STORAGE_CLASS" refers to below 2 ESLOG storage class parameters.
#ESLOG_MASTER_STORAGE_CLASS="${ESLOG_STORAGE_CLASS}"
#ESLOG_DATA_STORAGE_CLASS="${ESLOG_STORAGE_CLASS}"
##Provide ES_LOGS_HOSTNAME value in the format, "elasticsearch-<ES_LOGS_INSTANCE>-opendistro-es-data-svc"
#ES_LOGS_HOSTNAME="elasticsearch-logs-opendistro-es-data-svc"
##Provide the path of busybox registry present on the registry host. If it is present at /bbloc/busybox on registry host, provide its value as: /bbloc/busybox
#BUSYBOX_REGISTRY=external-library/busybox
##Provide the path of ES_LOGS_IMAGE_REGISTRY. eg: /logsimg/lphlx
#ES_LOGS_IMAGE_REGISTRY=bmc/lp00x

###############FTS#################
#ES_FTS_INSTANCE="fts"
##Provide ES_FTS_HOSTNAME value in the format, "elasticsearch-<ES_FTS_INSTANCE>-opendistro-es-data-svc"
#ES_FTS_HOSTNAME="elasticsearch-fts-opendistro-es-data-svc"
#ES_FTS_PORT="9200"
##In Uber pipeline, input parameter, "ELASTICSEARCH_FTS_STORAGE_CLASS" refers to below 2 ESFTS storage class parameters.
#ES_FTS_MASTER_STORAGE_CLASS="${ESFTS_STORAGE_CLASS}"
#ES_FTS_DATA_STORAGE_CLASS="${ESFTS_STORAGE_CLASS}"
#ES_FTS_MASTER_STORAGE_SIZE="10Gi"
#ES_FTS_DATA_STORAGE_SIZE="${ES_FTS_DATA_STORAGE_SIZE}Gi"
#ES_FTS_IMAGE_REGISTRY=bmc/lp00x

###############
#### RSSO #####
###############


#RSSO_ADMIN_USER="${RSSO_USER}"
#RSSO_ADMIN_PASSWORD="${RSSO_PASSWORD}"
#RSSO_EXTERNAL_URL="https://${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}-rsso.${CLUSTER_DOMAIN}/rsso"
RSSO_EXTERNAL_URL="${RSSO_URL}"
RSSO_SERVICE_URL="${RSSO_URL}"
RSSO_SAAS_URL="${RSSO_URL}"
#RSSO_SERVICE_URL="https://${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}-rsso.${CLUSTER_DOMAIN}/rsso"
#RSSO_SAAS_URL="https://${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}-rsso.${CLUSTER_DOMAIN}/rsso"

RSSO_ADMIN_USER="${RSSO_ADMIN_USER}"
RSSO_ADMIN_PASSWORD="${RSSO_ADMIN_PASSWORD}"
RSSO_REALM_ID="${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}"

DB_TYPE=""
DB_CONN_STR=""
RSSO_DB_HOSTNAME=""
RSSO_DB_NAME=""
RSSO_DB_USER=""
RSSO_DB_PASSWORD=""

########################################
#### SIDECAR CONTAINERS (Optional) #####
########################################

SIDECAR_FLUENT_ENABLE="${SIDECAR_FLUENTBIT}"
SIDECAR_FLUENT_ELASTICSEARCH_HOST="${LOGS_ELASTICSEARCH_HOSTNAME}"
SIDECAR_FLUENT_ELASTICSEARCH_PORT="${FLUENTBIT_LOGS_PORT}"
SIDECAR_FLUENT_OUTPUT_TYPE="${SIDECAR_FLUENT_OUTPUT_TYPE}"
SIDECAR_FLUENT_OUTPUT_CUSTOM='${SIDECAR_FLUENT_OUTPUT_CUSTOM}'
SIDECAR_FLUENT_DETAIL_LOG='${SIDECAR_FLUENT_DETAIL_LOG}'
SIDECAR_FLUENT_SPLUNK_TOKEN="${SIDECAR_FLUENT_SPLUNK_TOKEN}"
SIDECAR_FLUENT_SPLUNK_COMPRESS="${SIDECAR_FLUENT_SPLUNK_COMPRESS}"
SIDECAR_FLUENT_SPLUNK_CHANNEL="${SIDECAR_FLUENT_SPLUNK_CHANNEL}"
SIDECAR_FLUENT_SPLUNK_SEND_RAW="${SIDECAR_FLUENT_SPLUNK_SEND_RAW}"
SIDECAR_FLUENT_SPLUNK_EVENT_KEY="${SIDECAR_FLUENT_SPLUNK_EVENT_KEY}"
SIDECAR_FLUENT_SPLUNK_EVENT_INDEX="${SIDECAR_FLUENT_SPLUNK_EVENT_INDEX}"
SIDECAR_FLUENT_SPLUNK_EVENT_FIELD="${SIDECAR_FLUENT_SPLUNK_EVENT_FIELD}"
SIDECAR_FLUENT_SPLUNK_EVENT_SOURCE="${SIDECAR_FLUENT_SPLUNK_EVENT_SOURCE}"
SIDECAR_FLUENT_SPLUNK_EVENT_SOURCETYPE="${SIDECAR_FLUENT_SPLUNK_EVENT_SOURCETYPE}"
SIDECAR_FLUENT_TLS="${LOGS_ELASTICSEARCH_TLS_MODE}"
SIDECAR_FLUENT_AUTHENTICATION="${LOGS_ELASTICSEARCH_AUTHENTICATION_TYPE}"
SIDECAR_FLUENT_USER="elastic"
SIDECAR_FLUENT_PASSWORD='${LOGS_ELASTICSEARCH_PASSWORD}'

SIDECAR_FPACKAGER_ENABLE="${SIDECAR_SUPPORT_ASSISTANT}"

##################
#### PLATFORM ####
##################

###--------------------- PLATFORM DATABASE SERVICE PARAMETERS ---------------------###
AR_DB_ALWAYS_ON="No"
AR_DB_CASE_INSENSITIVE="T"
AR_SERVER_DB_TYPE="postgres"
AR_DB_HOSTNAME="DATABASE_HOST_NAME"  # AR DB server name
#Applicable for oracle db. But provide oracle db name to AR_DB_INSTANCE
AR_DB_INSTANCE="" 
#AR_DB_NAME="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_ar" # DB Name (PSR-DB)
#In case of oracle db, provide oracle service name (not SID) to AR_DB_NAME
AR_DB_NAME="${AR_DB_NAME}"
AR_DB_PORT="${AR_DB_PORT}"
#AR_DB_USER="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_aradmin" # DB USER
AR_DB_USER="${AR_DB_USER}"
AR_DB_PASSWORD="${AR_DB_PASSWORD}"  # DB Password
AR_DB_ODBC_USER=""
AR_DB_ODBC_PASSWORD=""
AR_DB_JDBC_URL="${AR_DB_JDBC_URL}"
AR_SERVER_DB_CHARACTER_SET="UTF-16"

AR_DATABASE_ROLE_NAME=""
AR_DATABASE_TABLESPACE_NAME=""
AR_DATABASE_TEMP_TABLESPACE_NAME=""
AR_DATA_FILENAME=""
AR_DB_DUMP_DIR=""
AR_DB_DUMP_FILE=""
AR_TEMP_FILENAME=""

PLATFORM_COMMON_ENABLE_ROOK_DEBUG="443"
PLATFORM_COMMON_ROOKOUT_CONTROLLER_HOST="wss://rook-controller.bmc.com"
PLATFORM_COMMON_MSP_DEPLOYMENT="false"
PLATFORM_ADMIN_REPLICA_COUNT="1"

## Parameters for FTS-ELASTICSEARCH (Elastic/Classic) ##
#In Uber pipeline, input parameter, "PLATFORM_FTS_TYPE" refers to this parameter.
PLATFORM_COMMON_FTS_TYPE="Elastic"
#For Elastic all parameters needs to updated
#For Classic no other parameters needs to updated
#Provide value of FTS_ELASTICSEARCH_HOSTNAME parameter from Uber pipeline.
PLATFORM_COMMON_FTS_ELASTIC_HOST="${FTS_ELASTICSEARCH_HOSTNAME}"
#Provide value of FTS_ELASTICSEARCH_PORT parameter from Uber pipeline.
PLATFORM_COMMON_FTS_ELASTIC_SEARCH_PORT="${FTS_ELASTICSEARCH_PORT}"
#Provide value of FTS_ELASTICSEARCH_USERNAME parameter from Uber pipeline.
PLATFORM_COMMON_FTS_ELASTIC_SEARCH_USERNAME="admin"
#Provide value of FTS_ELASTICSEARCH_USER_PASSWORD parameter from Uber pipeline.
PLATFORM_COMMON_FTS_ELASTIC_SEARCH_USER_PASSWORD="${FTS_ELASTICSEARCH_USER_PASSWORD}"
PLATFORM_COMMON_FTS_ELASTIC_SEARCH_SECURE="true"

## Hairpin Problem ##
# Set to true if cluster does not support Hairpin connections
PLATFORM_COMMON_MAP_EXT_SVC_TO_LOCALHOST="false"

## TLSv1.0 and TLSv1.1 ##
PLATFORM_COMMON_ENABLE_TLS_INSECURE_PROTOCOLS="false"
###--------------------- AR CONNECTION PARAMETERS ---------------------###
PLATFORM_ADMIN_EXTERNAL_HOST="" # External IP of Loadbalancer better give IP instead of name
PLATFORM_ADMIN_EXTERNAL_PORT=""
AR_USER="${AR_USER}"
AR_PASSWORD='${AR_PASSWORD}'
###--------------------- AR SERVICE PASSWORD PARAMETERS ---------------------###
AR_SERVER_APP_SERVICE_PASSWORD="${AR_SERVER_APP_SERVICE_PASSWORD}"
AR_SERVER_DSO_USER_PASSWORD=""
AR_SERVER_MIDTIER_SERVICE_PASSWORD=""

## External Access ##
# # To enable external access, fill the external IPs in json list format, like "[10.168.0.1,10.168.0.2]"
PLATFORM_ADMIN_PLATFORM_EXTERNAL_IPS=""  # External IP of Loadbalancer 

# NOTE:  Platform-admin routes and ingress are not used by Operations in production.
## Route ##
PLATFORM_ADMIN_ROUTE_ENABLED="false"
PLATFORM_ADMIN_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-adminip"
PLATFORM_ADMIN_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## INGRESS ##
PLATFORM_ADMIN_INGRESS_ENABLED="false"  # true
PLATFORM_ADMIN_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-adminip"  # Host URL
PLATFORM_ADMIN_INGRESS_DOMAIN="${CLUSTER_DOMAIN}" # domain name

PLATFORM_USER_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"
PLATFORM_USER_INGRESS_ENABLED="${ingress_enabled}"
PLATFORM_USER_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-is"


PLATFORM_USER_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"
PLATFORM_USER_ROUTE_ENABLED="${route_enabled}"
PLATFORM_USER_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-is"


PLATFORM_FTS_PLATFORM_EXTERNAL_IPS=""

PLATFORM_SR_INGRESS_DOMAIN=""
PLATFORM_SR_INGRESS_ENABLED="false"
PLATFORM_SR_INGRESS_HOST=""

PLATFORM_SR_ROUTE_DOMAIN=""
PLATFORM_SR_ROUTE_ENABLED="false"
PLATFORM_SR_ROUTE_HOST=""

### AR LICENSE KEY(if any otherwise keep blank) ###
PLATFORM_ADMIN_LICENSE_KEY=""

###--------------------- PLATFORM COMMON SERVICE PARAMETERS ---------------------###
PLATFORM_COMMON_CMDB_REDIRECT_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-restapi.${CLUSTER_DOMAIN}/cmdb/index.html" # Needs to be configured
PLATFORM_COMMON_DEFAULT_WEB_PATH="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}.${CLUSTER_DOMAIN}/arsys" # Needs to be configured
PLATFORM_COMMON_AR_SERVER_ALIAS="${AR_SERVER_ALIAS}"
PLATFORM_COMMON_AR_SERVER_DOMAIN="${CLUSTER_DOMAIN}"  # Needs to be configured
PLATFORM_COMMON_RSSO_AGENTID="${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}"

# Implicitly defaults to changeit if empty
PLATFORM_COMMON_CACERTS_SSL_TRUSTSTORE_PASSWORD='${CACERTS_SSL_TRUSTSTORE_PASSWORD}'

#################
#### MIDTIER ####
#################

MIDTIER_COMMON_ESCHAT_SERVER_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-vchat.${CLUSTER_DOMAIN}/eschat" # Needs to be configured
MIDTIER_COMMON_MSP_DEPLOYMENT=""
MIDTIER_COMMON_RSSO_AGENTID="${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}" # Project name /or Kubernetes namespace Non-mandatory
MIDTIERCACHEBUILDER_TRIGGER_PRELOAD="false"
MIDTIERCACHEBUILDER_VIEWSTATS_DOWNLOAD="true"
MIDTIERCACHEBUILDER_USE_PREFETCH_CFG="true"
MIDTIERCACHEBUILDER_SCHEDULE="${MIDTIERCACHEBUILDER_SCHEDULE}"

## Route ##
MIDTIER_USER_ROUTE_ENABLED="${route_enabled}"
MIDTIER_USER_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}"
MIDTIER_USER_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## Ingress ##
MIDTIER_USER_INGRESS_ENABLED="${ingress_enabled}"
MIDTIER_USER_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}" # Url name of ingress to midtier
MIDTIER_USER_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"

## Route ##
MIDTIER_INT_ROUTE_ENABLED="${route_enabled}"
MIDTIER_INT_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-int"
MIDTIER_INT_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## Ingress ##
MIDTIER_INT_INGRESS_ENABLED="${ingress_enabled}"
MIDTIER_INT_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-int" # Url name of ingress to midtier
MIDTIER_INT_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"


##################
#### SMART IT ####
##################

###--------------------- SMARTIT COMMON PARAMETERS ---------------------###
SMARTIT_CHAT_SERVER_ADMIN_BOSH_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit.${CLUSTER_DOMAIN}/http-bind/"
SMARTIT_CHAT_SERVER_ADMIN_CLIENT_PORT="5222"
SMARTIT_CHAT_SERVER_ADMIN_CM_HOST="openfire"
SMARTIT_CHAT_SERVER_ADMIN_DOMAIN="openfire"
SMARTIT_MSP_DEPLOYMENT=""
SMARTIT_SESSION_TIMEOUT=30
SMARTIT_HOST_ALIAS=""

###--------------------- SMARTIT DATABASE PARAMETERS ---------------------###
SMARTIT_DB_ALWAYS_ON="No"
SMARTIT_DB_TYPE="postgres"
SMARTIT_DB_HOSTNAME="DATABASE_HOST_NAME"  # DB HOST name
#Applicable for oracle db. But provide oracle db name to SMARTIT_DB_INSTANCE
SMARTIT_DB_INSTANCE=""
#SMARTIT_DB_NAME="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_smartit" # Name of DB
#In case of oracle db, provide oracle service name (not SID) to SMARTIT_DB_NAME
SMARTIT_DB_NAME=""
SMARTIT_DB_PORT="5432"
## System ##
#SMARTIT_DB_USER_SYSTEM="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_smartit_systemadmin" # Name of DB
SMARTIT_DB_USER_SYSTEM=""
SMARTIT_DB_PASSWORD_SYSTEM=""
## Business #
#SMARTIT_DB_USER_BUSINESS="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_smartit_businessadmin" # Name of DB
SMARTIT_DB_USER_BUSINESS=""
SMARTIT_DB_PASSWORD_BUSINESS="" 

###--------------------- SMARTIT PASSWORD PARAMETERS ---------------------###
SMARTIT_CHAT_SERVER_ADMIN_LOGIN="admin"
SMARTIT_CHAT_SERVER_ADMIN_PASSWORD="${SMARTIT_CHAT_SERVER_ADMIN_PWD}"

##------------------SMARTIT Integration URLS PARAMETERS ---------------------###
SMARTIT_MASTER_MIDTIER_BASE_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}.${CLUSTER_DOMAIN}" # SmartIT URL - midtier
SMARTIT_MASTER_ES_CHAT_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-vchat.${CLUSTER_DOMAIN}" # SmartIT URL - midtier
SMARTIT_MASTER_DWP_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-dwp.${CLUSTER_DOMAIN}" # SmartIT URL - midtier
SMARTIT_MASTER_SMARTIT_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit.${CLUSTER_DOMAIN}"
SMARTIT_MASTER_HELIXDASHBOARD_URL=""

## Route ##
SMARTIT_MASTER_ROUTE_ENABLED="${route_enabled}"
SMARTIT_MASTER_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit"
SMARTIT_MASTER_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## Ingress ##
SMARTIT_MASTER_INGRESS_ENABLED="${ingress_enabled}"
SMARTIT_MASTER_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit" # SmartIT host route
SMARTIT_MASTER_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"


## Route ##
SMARTIT_SLAVE_ROUTE_ENABLED="${route_enabled}"
SMARTIT_SLAVE_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit"
SMARTIT_SLAVE_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## Ingress ##
SMARTIT_SLAVE_INGRESS_ENABLED="${ingress_enabled}"
SMARTIT_SLAVE_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit" # SmartIT host route
SMARTIT_SLAVE_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"

SMARTIT_IS_SECURE_PROTOCOL="true"
SMARTIT_PORT="443"

###################################
#### SMARTREPORTING PARAMETERS ####
###################################

###--------------------- SMARTREPORTING DATABASE PARAMETERS ---------------------###
SMARTREPORTING_DB_ALWAYS_ON="No"
SMARTREPORTING_DB_TYPE="postgres"
SMARTREPORTING_DB_HOSTNAME="DATABASE_HOST_NAME"  # DB Host 
#Applicable for oracle db. But provide oracle db name to SMARTREPORTING_DB_INSTANCE_NAME
SMARTREPORTING_DB_INSTANCE_NAME=""
SMARTREPORTING_DB_PORT="5432"
#SMARTREPORTING_DB_NAME="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_sr" # DB Name
#In case of oracle db, provide oracle service name (not SID) to SMARTREPORTING_DB_NAME
SMARTREPORTING_DB_NAME=""
#SMARTREPORTING_DB_USER="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_sradmin" # DB User
SMARTREPORTING_DB_USER=""
SMARTREPORTING_DB_PASSWORD="${SMARTREPORTING_DB_PASSWORD}"

###--------------------- SMARTREPORTING PASSWORD PARAMETERS ---------------------###
SMARTREPORTING_ADMIN_USER="siadmin"
SMARTREPORTING_ADMIN_CURRENT_PASSWORD="siadmin"
SMARTREPORTING_ADMIN_NEW_PASSWORD="${SMARTREPORTING_ADMIN_NEW_PWD}"
SMARTREPORTING_SERVICE_USER_PASSWORD="${SMARTREPORTING_SERVICE_USER_PWD}"

SMARTREPORTING_REPORTS_EVENT_CACHE_MAX_DAYS="30"
SMARTREPORTING_REPORTS_EVENT_CACHE_SIZE="20000"
SMARTREPORTING_REPORTS_TRANSLATION_CACHE_SIZE="5000"

SMARTREPORTING_EXTERNAL_INSTANCE_BASE_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-sr.${CLUSTER_DOMAIN}/AdminConsole/sharereport.jsp/"

#SMARTREPORTING_X_FRAME_OPTIONS='ALLOW-FROM https://psr-aws-oregon.bmc.com/'
SMARTREPORTING_X_FRAME_OPTIONS='ALLOW-FROM https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}.${CLUSTER_DOMAIN}'
SMARTREPORTING_REPORTS_EXECUTIONQUEUE_INITIAL_WAITTIME="5"

## Route ##
SMARTREPORTING_ROUTE_ENABLED="${route_enabled}"
SMARTREPORTING_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-sr"
SMARTREPORTING_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## Ingress ##
SMARTREPORTING_INGRESS_ENABLED="${ingress_enabled}"
SMARTREPORTING_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-sr" # Ingress route URL
SMARTREPORTING_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"


######################
#### ATRIUMWEBSVC ####
######################

ATWS_SVC_NAME="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-atws.${CLUSTER_DOMAIN}" # Atrium Web URL

ATWS_UDDI_ADMIN_USERNAME="admin"
ATWS_UDDI_ADMIN_PASSWORD="${ATWS_UDDI_ADMIN_PWD}"

ATWS_UDDI_DB_TYPE="postgres"
ATWS_UDDI_DB_SERVER_NAME="DATABASE_HOST_NAME" # DB Host
ATWS_UDDI_DB_SERVER_PORT="5432"
#ATWS_UDDI_DB_NAME="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_ar" # DB Name
#In case of oracle db, provide oracle service name (not SID) to ATWS_UDDI_DB_NAME
#ATWS_UDDI_DB_NAME="${AR_DB_NAME}"
ATWS_UDDI_DB_NAME="${ATWS_DB_NAME}"
#ATWS_UDDI_DB_USERNAME="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_aradmin" # DB User
ATWS_UDDI_DB_USERNAME="${AR_DB_USER}"
ATWS_UDDI_DB_USER_PASSWORD="${AR_DB_PASSWORD}"
ATWS_UDDI_JDBC_URL="${AR_DB_JDBC_URL}"

###--------------------- ATRIUMWEBSVC SERVICE PARAMETERS ---------------------###
ATWS_JAVA_MAX_HEAP_SIZE="-Xmx1536m"
ATWS_JAVA_MIN_HEAP_SIZE="-Xms1536m"

## Route ##
ATWS_ROUTE_ENABLED="${route_enabled}"
ATWS_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-atws"
ATWS_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## Ingress ##
ATWS_INGRESS_ENABLED="${ingress_enabled}"
ATWS_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-atws" # Atrium Web Service ingress URL
ATWS_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"


###########################
#### VIRTUALCHATSERVER ####
###########################
VC_CHAT_PRODUCT="livechat"
VC_LB_SERVER_NAME="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-vchat.${CLUSTER_DOMAIN}"
VC_LB_PORT="443"
VC_LB_PROTOCOL="https"
VC_RKM_USER_NAME=""
VC_RKM_PASSWORD=""
VC_PROXY_USER_LOGIN_NAME=""
VC_PROXY_USER_PASSWORD=""

VIRTUALCHATSERVER_MIDTIER_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}.${CLUSTER_DOMAIN}"
VIRTUALCHATSERVER_SMARTIT_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit.${CLUSTER_DOMAIN}"
VIRTUALCHATSERVER_BWF_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-is.${CLUSTER_DOMAIN}"
VIRTUALCHATSERVER_REPLICA_COUNT="2"
VIRTUALCHATSERVER_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
VIRTUALCHATSERVER_JAVA_MIN_HEAP_SIZE="-Xms1024m"

## Route ##
VIRTUALCHATSERVER_ROUTE_ENABLED="${route_enabled}"
VIRTUALCHATSERVER_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-vchat"
VIRTUALCHATSERVER_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## Ingress ##
VIRTUALCHATSERVER_INGRESS_ENABLED="${ingress_enabled}"
VIRTUALCHATSERVER_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-vchat"
VIRTUALCHATSERVER_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"


##################
#### OPENFIRE ####
##################
OPENFIRE_REPLICA_COUNT=2
## ex. OPENFIRE_AUTH_RESOURCE=${SMARTIT_MASTER_SMARTIT_URL}/smartit/rest/users/chat"
OPENFIRE_AUTH_RESOURCE="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit.${CLUSTER_DOMAIN}/smartit/rest/users/chat"
OPENFIRE_ADMIN_USER_PASSWORD="${OPENFIRE_ADMIN_USER_PWD}"
OPENFIRE_DB_ALWAYS_ON="No"
OPENFIRE_DB_SERVER_NAME="DATABASE_HOST_NAME"
OPENFIRE_DB_PORT="${AR_DB_PORT}"
# In case of oracle db, provide oracle service name (not SID) to OPENFIRE_DB_NAME
OPENFIRE_DB_NAME="${AR_DB_NAME}"
#OPENFIRE_DB_USER_NAME="${CUSTOMER_SERVICE_NAME}_${DB_ENVIRONMENT}_openfireadmin"
OPENFIRE_DB_USER_NAME="${AR_DB_USER}"
OPENFIRE_DB_USER_PASSWORD="${AR_DB_PASSWORD}"
OPENFIRE_LOGZIPPER_ENABLED="false"
OPENFIRE_JDBC_URL="${AR_DB_JDBC_URL}"

###--------------------- OPENFIRE PLUGIN SERVICE PARAMETERS ---------------------###
OPENFIRE_JAVA_MIN_HEAP_SIZE="-Xms1024m"
OPENFIRE_JAVA_MAX_HEAP_SIZE="-Xmx1024m"

## INGRESS ##
OPENFIRE_INGRESS_ENABLED="${ingress_enabled}"
#OPENFIRE_INGRESS_HOST="psr-aws-oregon-chat.dsmlab"
#OPENFIRE_INGRESS_DOMAIN="bmc.com"
OPENFIRE_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-chat"
OPENFIRE_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"

## Route ##
OPENFIRE_ROUTE_ENABLED="${route_enabled}"
OPENFIRE_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-chat"
OPENFIRE_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## http bind Route ##
OPENFIRE_HTTPBINDROUTE_ENABLED="${route_enabled}"
OPENFIRE_HTTPBINDROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit"
OPENFIRE_HTTPBINDROUTE_DOMAIN="${CLUSTER_DOMAIN}"


## http bind INGRESS ##
OPENFIRE_HTTPBINDINGRESS_ENABLED="${ingress_enabled}"
OPENFIRE_HTTPBINDINGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-smartit"
OPENFIRE_HTTPBINDINGRESS_DOMAIN="${CLUSTER_DOMAIN}"


####################################################################################################################################################################################
##################
#### PLATFORM ####
##################

###--------------------- PLATFORM DATABASE SERVICE PARAMETERS ---------------------###
#AR_DB_ALWAYS_ON="Yes"
#AR_SERVER_DB_TYPE="mssql"
#AR_DB_HOSTNAME="pun-sqacluster2.bmc.com"
#AR_DB_INSTANCE=""
#AR_DB_NAME="psr-aws-oregon_ar"
#AR_DB_PORT="1433"
#AR_DB_USER="psr-aws-oregon_aradmin"
#AR_DB_PASSWORD=""

PLATFORM_COMMON_AR_MON_VAR_ARDATE=""
PLATFORM_COMMON_AR_MON_VAR_ARDATEONLY=""
PLATFORM_COMMON_AR_MON_VAR_ARTIMEONLY=""
PLATFORM_COMMON_AR_MON_VAR_TZ=""
PLATFORM_COMMON_AR_MON_VAR_JAVA_TOOL_OPTIONS=""
PLATFORM_COMMON_AR_HOST_ALIAS=""

# SaaS Admin User credentials. If set, it will be used for applying configuration template.
# If not provided, it will use RAS user.
# In that case if some configs in tempalte are present in restriction list then those configs will not be applied and warning will be logged in log file
#PLATFORM_COMMON_SAAS_ADMIN_USER=""
#PLATFORM_COMMON_SAAS_ADMIN_PASSWORD=""


###--------------------- PLATFORM-ADMIN SERVICE PARAMETERS ---------------------###
PLATFORM_ADMIN_ENABLE_SERVICES="email_engine,reconciliation,normalization,approval_plugin,reporting_plugin,diserver,flashboard"
PLATFORM_ADMIN_APPROVAL_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_ADMIN_APPROVAL_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_ADMIN_AR_MONITOR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_ADMIN_AR_MONITOR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_ADMIN_AR_SERVER_JAVA_OPTS=""
PLATFORM_ADMIN_ATRIUM_PLUGIN_JAVA_MIN_HEAP_SIZE=""
PLATFORM_ADMIN_ATRIUM_PLUGIN_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_ADMIN_AUTH_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_ADMIN_AUTH_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_ADMIN_CARTE_SVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_ADMIN_CARTE_SVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_ADMIN_MAIN_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_ADMIN_MAIN_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_ADMIN_EMAIL_ENGINE_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_ADMIN_EMAIL_ENGINE_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_ADMIN_NORMALIZATION_JAVA_MIN_HEAP_SIZE=""
PLATFORM_ADMIN_NORMALIZATION_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_ADMIN_REPORTING_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_ADMIN_REPORTING_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx512m"

PLATFORM_ADMIN_FLASHBOARDSVR_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_ADMIN_FLASHBOARDSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_ADMIN_FILEDEPLOYER_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_ADMIN_FILEDEPLOYER_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_ADMIN_AR_SVRD_JAVA_MIN_HEAP_SIZE=""
PLATFORM_ADMIN_AR_SVRD_JAVA_MAX_HEAP_SIZE=""

## volumeMounts ##
PLATFORM_ADMIN_VOLUME_MOUNT_ENABLED="true"

## volumes ##
PLATFORM_ADMIN_VOLUME_ENABLED="true"


## RESOURCES ##
PLATFORM_ADMIN_MEMORY_REQUEST="10Gi"
PLATFORM_ADMIN_CPU_REQUEST="2"
PLATFORM_ADMIN_MEMORY_LIMIT="15Gi"
PLATFORM_ADMIN_CPU_LIMIT="4"

## LOGZIPPER ##
PLATFORM_ADMIN_LOGZIPPER_ENABLED="false"

# Config template params
#PLATFORM_ADMIN_CONFIGURATION_TEMPLATE_NAME=""
#PLATFORM_ADMIN_APPLY_CONFIGURATION_TEMPLATE_FORCE="false"



###--------------------- PLATFORM-FTS SERVICE PARAMETERS ---------------------###
PLATFORM_FTS_REPLICA_COUNT=2
PLATFORM_FTS_ENABLE_SERVICES="email_engine,reconciliation,normalization,approval_plugin,reporting_plugin,diserver,flashboard"
PLATFORM_FTS_APPROVAL_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_FTS_APPROVAL_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_FTS_AR_MONITOR_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_FTS_AR_MONITOR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_FTS_AR_SERVER_JAVA_OPTS=""
PLATFORM_FTS_ATRIUM_PLUGIN_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_FTS_ATRIUM_PLUGIN_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_FTS_AUTH_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_FTS_AUTH_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_FTS_CARTE_SVR_JAVA_MIN_HEAP_SIZE="-Xms1024m"
PLATFORM_FTS_CARTE_SVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_FTS_MAIN_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms1024m"
PLATFORM_FTS_MAIN_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_FTS_EMAIL_ENGINE_JAVA_MIN_HEAP_SIZE="-Xms1024m"
PLATFORM_FTS_EMAIL_ENGINE_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_FTS_NORMALIZATION_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_FTS_NORMALIZATION_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_FTS_REPORTING_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_FTS_REPORTING_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_FTS_FLASHBOARDSVR_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_FTS_FLASHBOARDSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_FTS_FILEDEPLOYER_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_FTS_FILEDEPLOYER_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_FTS_AR_SVRD_JAVA_MIN_HEAP_SIZE="8589934592"
PLATFORM_FTS_AR_SVRD_JAVA_MAX_HEAP_SIZE="8589934592"
PLATFORM_FTS_FTS_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_FTS_FTS_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_FTS_ARPROBE_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_FTS_ARPROBE_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_FTS_ARSERVER_LAUNCHER_JAVA_MIN_HEAP_SIZE="-Xms32m"
PLATFORM_FTS_ARSERVER_LAUNCHER_JAVA_MAX_HEAP_SIZE="-Xmx32m"
PLATFORM_FTS_SYNTHETIC_MONITOR_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_FTS_SYNTHETIC_MONITOR_JAVA_MAX_HEAP_SIZE="-Xmx128m"

## volumeMounts ##
PLATFORM_FTS_VOLUME_MOUNT_ENABLED="true"

## volumes ##
PLATFORM_FTS_VOLUME_ENABLED="true"

## volumeClaimTemplate ##
PLATFORM_FTS_VOLUME_CLAIM_TEMPLATE_ENABLED="true"
PLATFORM_FTS_VOLUME_CLAIM_TEMPLATE_STORAGE_CLASS=""
PLATFORM_FTS_VOLUME_CLAIM_TEMPLATE_STORAGE_SIZE="5Gi"

## RESOURCES ##
PLATFORM_FTS_MEMORY_REQUEST="14Gi"
PLATFORM_FTS_CPU_REQUEST="100m"
PLATFORM_FTS_MEMORY_LIMIT="16Gi"
PLATFORM_FTS_CPU_LIMIT="4"

## LOGZIPPER ##
PLATFORM_FTS_LOGZIPPER_ENABLED="false"

# Config template params
#PLATFORM_FTS_CONFIGURATION_TEMPLATE_NAME=""
#PLATFORM_FTS_APPLY_CONFIGURATION_TEMPLATE_FORCE="false"

## initimage ##
PLATFORM_FTS_INITIMAGE="true"



###--------------------- PLATFORM-USER SERVICE PARAMETERS ---------------------###
PLATFORM_USER_REPLICA_COUNT=2
PLATFORM_USER_ENABLE_SERVICES="normalization,approval_plugin,reporting_plugin,diserver"
PLATFORM_USER_APPROVAL_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_USER_APPROVAL_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_USER_AR_MONITOR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_USER_AR_MONITOR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_USER_AR_SERVER_JAVA_OPTS=""
PLATFORM_USER_ATRIUM_PLUGIN_JAVA_MIN_HEAP_SIZE=""
PLATFORM_USER_ATRIUM_PLUGIN_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_USER_AUTH_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_USER_AUTH_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_USER_CARTE_SVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_USER_CARTE_SVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_USER_MAIN_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms1024m"
PLATFORM_USER_MAIN_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_USER_EMAIL_ENGINE_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_USER_EMAIL_ENGINE_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_USER_NORMALIZATION_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_USER_NORMALIZATION_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_USER_REPORTING_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_USER_REPORTING_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_USER_FLASHBOARDSVR_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_USER_FLASHBOARDSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_USER_FILEDEPLOYER_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_USER_FILEDEPLOYER_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_USER_AR_SVRD_JAVA_MIN_HEAP_SIZE="8589934592"
PLATFORM_USER_AR_SVRD_JAVA_MAX_HEAP_SIZE="8589934592"
PLATFORM_USER_ARPROBE_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_USER_ARPROBE_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_USER_SYNTHETIC_MONITOR_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_USER_SYNTHETIC_MONITOR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_USER_ARSERVER_LAUNCHER_JAVA_MIN_HEAP_SIZE="-Xms32m"
PLATFORM_USER_ARSERVER_LAUNCHER_JAVA_MAX_HEAP_SIZE="-Xmx32m"

## volumeMounts ##
PLATFORM_USER_VOLUME_MOUNT_ENABLED="true"

## volumes ##
PLATFORM_USER_VOLUME_ENABLED="true"

## External Access ##
# To enable external access, fill the external IPs in json list format, like "[10.168.0.1,10.168.0.2]"
PLATFORM_USER_PLATFORM_EXTERNAL_IPS=""

## RESOURCES ##
PLATFORM_USER_MEMORY_REQUEST="11Gi"
PLATFORM_USER_CPU_REQUEST="100m"
PLATFORM_USER_MEMORY_LIMIT="14Gi"
PLATFORM_USER_CPU_LIMIT="5.75"

## LOGZIPPER ##
PLATFORM_USER_LOGZIPPER_ENABLED="false"

## set true for parallel platform-user pod deployment ##
PLATFORM_USER_PARALLELDEPLOYMENT_ENABLED="false"

# Config template params
#PLATFORM_USER_CONFIGURATION_TEMPLATE_NAME=""
#PLATFORM_USER_APPLY_CONFIGURATION_TEMPLATE_FORCE="false"

## initimage ##
PLATFORM_USER_INITIMAGE="false"



###--------------------- PLATFORM-SR SERVICE PARAMETERS ---------------------###
PLATFORM_SR_REPLICA_COUNT=2
PLATFORM_SR_APPROVAL_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_SR_APPROVAL_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_SR_AR_MONITOR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_SR_AR_MONITOR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_SR_AR_SERVER_JAVA_OPTS=""
PLATFORM_SR_ATRIUM_PLUGIN_JAVA_MIN_HEAP_SIZE=""
PLATFORM_SR_ATRIUM_PLUGIN_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_SR_AUTH_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_SR_AUTH_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_SR_CARTE_SVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_SR_CARTE_SVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_SR_MAIN_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_SR_MAIN_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_SR_EMAIL_ENGINE_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_SR_EMAIL_ENGINE_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_SR_NORMALIZATION_JAVA_MIN_HEAP_SIZE=""
PLATFORM_SR_NORMALIZATION_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_SR_REPORTING_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_SR_REPORTING_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_SR_FLASHBOARDSVR_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_SR_FLASHBOARDSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_SR_FILEDEPLOYER_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_SR_FILEDEPLOYER_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_SR_AR_SVRD_JAVA_MIN_HEAP_SIZE="8589934592"
PLATFORM_SR_AR_SVRD_JAVA_MAX_HEAP_SIZE="8589934592"
PLATFORM_SR_ARPROBE_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_SR_ARPROBE_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_SR_ARSERVER_LAUNCHER_JAVA_MIN_HEAP_SIZE="-Xms32m"
PLATFORM_SR_ARSERVER_LAUNCHER_JAVA_MAX_HEAP_SIZE="-Xmx32m"
PLATFORM_SR_SYNTHETIC_MONITOR_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_SR_SYNTHETIC_MONITOR_JAVA_MAX_HEAP_SIZE="-Xmx256m"

## volumeMounts ##
PLATFORM_SR_VOLUME_MOUNT_ENABLED="true"


## volumes ##
PLATFORM_SR_VOLUME_ENABLED="true"

## RESOURCES ##
PLATFORM_SR_MEMORY_REQUEST="9Gi"
PLATFORM_SR_CPU_REQUEST="100m"
PLATFORM_SR_MEMORY_LIMIT="11Gi"
PLATFORM_SR_CPU_LIMIT="4"

## LOGZIPPER ##
PLATFORM_SR_LOGZIPPER_ENABLED="false"

# Config template params
#PLATFORM_SR_CONFIGURATION_TEMPLATE_NAME=""
#PLATFORM_SR_APPLY_CONFIGURATION_TEMPLATE_FORCE="false"

## initimage ##
PLATFORM_SR_INITIMAGE="false"



###--------------------- PLATFORM-INT SERVICE PARAMETERS ---------------------###
PLATFORM_INT_REPLICA_COUNT=2
PLATFORM_INT_ENABLE_SERVICES=""
PLATFORM_INT_APPROVAL_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_INT_APPROVAL_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_INT_AR_MONITOR_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_INT_AR_MONITOR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_INT_AR_SERVER_JAVA_OPTS=""
PLATFORM_INT_ATRIUM_PLUGIN_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_INT_ATRIUM_PLUGIN_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_INT_AUTH_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_INT_AUTH_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_INT_CARTE_SVR_JAVA_MIN_HEAP_SIZE="-Xms1024m"
PLATFORM_INT_CARTE_SVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_INT_MAIN_PLUGINSVR_JAVA_MIN_HEAP_SIZE="-Xms1024m"
PLATFORM_INT_MAIN_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_INT_EMAIL_ENGINE_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_INT_EMAIL_ENGINE_JAVA_MAX_HEAP_SIZE="-Xmx1024m"
PLATFORM_INT_NORMALIZATION_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_INT_NORMALIZATION_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_INT_REPORTING_PLUGINSVR_JAVA_MIN_HEAP_SIZE=""
PLATFORM_INT_REPORTING_PLUGINSVR_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_INT_FLASHBOARDSVR_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_INT_FLASHBOARDSVR_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_INT_FILEDEPLOYER_JAVA_MIN_HEAP_SIZE="-Xms128m"
PLATFORM_INT_FILEDEPLOYER_JAVA_MAX_HEAP_SIZE="-Xmx256m"
PLATFORM_INT_AR_SVRD_JAVA_MIN_HEAP_SIZE="8589934592"
PLATFORM_INT_AR_SVRD_JAVA_MAX_HEAP_SIZE="8589934592"
PLATFORM_INT_ARPROBE_JAVA_MIN_HEAP_SIZE="-Xms512m"
PLATFORM_INT_ARPROBE_JAVA_MAX_HEAP_SIZE="-Xmx512m"
PLATFORM_INT_ARSERVER_LAUNCHER_JAVA_MIN_HEAP_SIZE="-Xms32m"
PLATFORM_INT_ARSERVER_LAUNCHER_JAVA_MAX_HEAP_SIZE="-Xmx32m"
PLATFORM_INT_SYNTHETIC_MONITOR_JAVA_MIN_HEAP_SIZE="-Xms256m"
PLATFORM_INT_SYNTHETIC_MONITOR_JAVA_MAX_HEAP_SIZE="-Xmx256m"

## volumeMounts ##
PLATFORM_INT_VOLUME_MOUNT_ENABLED="true"

## volumes ##
PLATFORM_INT_VOLUME_ENABLED="true"

## External Access ##
# To enable external access, fill the external IPs in json list format, like "[10.168.0.1,10.168.0.2]"
PLATFORM_INT_PLATFORM_EXTERNAL_IPS=""

## Route ##
PLATFORM_INT_ROUTE_ENABLED="${route_enabled}"
PLATFORM_INT_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-restapi"
PLATFORM_INT_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"

## INGRESS ##
PLATFORM_INT_INGRESS_ENABLED="${ingress_enabled}"
PLATFORM_INT_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-restapi"
PLATFORM_INT_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"

## RESOURCES ##
PLATFORM_INT_MEMORY_REQUEST="9Gi"
PLATFORM_INT_CPU_REQUEST="100m"
PLATFORM_INT_MEMORY_LIMIT="11Gi"
PLATFORM_INT_CPU_LIMIT="4"

## LOGZIPPER ##
PLATFORM_INT_LOGZIPPER_ENABLED="false"

# Config template params
#PLATFORM_INT_CONFIGURATION_TEMPLATE_NAME=""
#PLATFORM_INT_APPLY_CONFIGURATION_TEMPLATE_FORCE="false"

## initimage ##
PLATFORM_INT_INITIMAGE="false"


###---------- PLATFORMUPGRADE JOB CONTAINER (UPGRADE-ONLY) ----------###
# Run Archiver tool to set archiving durations
PLATFORMUPGRADE_RUN_ARCHIVER_TOOL="true"

# Duration in days, -1 to disable
PLATFORMUPGRADE_ARCHIVE_DURATION="730"

# True to force overwriting existing valid archive duration
PLATFORMUPGRADE_FORCE_ARCHIVER="false"






#################
#### MIDTIER ####
#################

###--------------------- MIDTIER-USER SERVICE PARAMETERS ---------------------###
MIDTIER_USER_REPLICA_COUNT="2"
MIDTIER_USER_JAVA_HEAP_MIN="-Xms6G"
MIDTIER_USER_JAVA_HEAP_MAX="-Xmx6G"

## volumeMounts ##
MIDTIER_USER_VOLUME_MOUNT_ENABLED="true"

## volumes ##
MIDTIER_USER_VOLUME_ENABLED="true"

## volumeClaimTemplate ##
MIDTIER_USER_VOLUME_CLAIM_TEMPLATE_ENABLED="true"
MIDTIER_USER_VOLUME_CLAIM_TEMPLATE_STORAGE_CLASS=""
MIDTIER_USER_VOLUME_CLAIM_TEMPLATE_STORAGE_SIZE="2Gi"



## Resources ##
MIDTIER_USER_MEMORY_REQUEST="6Gi"
MIDTIER_USER_CPU_REQUEST="100m"
MIDTIER_USER_MEMORY_LIMIT="8Gi"
MIDTIER_USER_CPU_LIMIT="4"

## Logzipper ##
MIDTIER_USER_LOGZIPPER_ENABLED="false"


###--------------------- MIDTIER-INT SERVICE PARAMETERS ---------------------###
MIDTIER_INT_REPLICA_COUNT="2"
MIDTIER_INT_JAVA_HEAP_MIN="-Xms1536m"
MIDTIER_INT_JAVA_HEAP_MAX="-Xmx1536m"

## volumeMounts ##
MIDTIER_INT_VOLUME_MOUNT_ENABLED="true"

## volumes ##    # Need to check
MIDTIER_INT_VOLUME_ENABLED="true"

## volumeClaimTemplate ##
MIDTIER_INT_VOLUME_CLAIM_TEMPLATE_ENABLED="true"
MIDTIER_INT_VOLUME_CLAIM_TEMPLATE_STORAGE_CLASS=""
MIDTIER_INT_VOLUME_CLAIM_TEMPLATE_STORAGE_SIZE="2Gi"



## Resources ##
MIDTIER_INT_MEMORY_REQUEST="2Gi"
MIDTIER_INT_CPU_REQUEST="100m"
MIDTIER_INT_MEMORY_LIMIT="3Gi"
MIDTIER_INT_CPU_LIMIT="1"

## Logzipper ##
MIDTIER_INT_LOGZIPPER_ENABLED="false"





##################
#### SMART IT ####
##################

###--------------------- SMARTIT MASTER SERVICE PARAMETERS ---------------------###
SMARTIT_MASTER_REPLICA_COUNT=1
SMARTIT_MASTER_JAVA_MAX_HEAP_SIZE="-Xmx6144m"
SMARTIT_MASTER_JAVA_MIN_HEAP_SIZE="-Xms6144m"
SMARTIT_MASTER_PERF_LOG_MONITOR_JAVA_MIN_HEAP_SIZE=""
SMARTIT_MASTER_PERF_LOG_MONITOR_JAVA_MAX_HEAP_SIZE=""
SMARTIT_MASTER_DB_FILESYNC_JAVA_MIN_HEAP_SIZE=""
SMARTIT_MASTER_DB_FILESYNC_JAVA_MAX_HEAP_SIZE=""
SMARTIT_MASTER_NON_HEAP_SIZE=""

## Resources ##
SMARTIT_MASTER_MEMORY_REQUEST="7Gi"
SMARTIT_MASTER_CPU_REQUEST="100m"
SMARTIT_MASTER_MEMORY_LIMIT="8Gi"
SMARTIT_MASTER_CPU_LIMIT="4"
SMARTIT_MASTER_VOLUME_MOUNT_ENABLED="true"
SMARTIT_MASTER_VOLUME_ENABLED="true"

## Logzipper ##
SMARTIT_MASTER_LOGZIPPER_ENABLED="false"


###--------------------- SMARTIT SLAVE SERVICE PARAMETERS ---------------------###
SMARTIT_SLAVE_REPLICA_COUNT=1
SMARTIT_SLAVE_JAVA_MAX_HEAP_SIZE="-Xmx6144m"
SMARTIT_SLAVE_JAVA_MIN_HEAP_SIZE="-Xms6144m"
SMARTIT_SLAVE_PERF_LOG_MONITOR_JAVA_MIN_HEAP_SIZE=""
SMARTIT_SLAVE_PERF_LOG_MONITOR_JAVA_MAX_HEAP_SIZE=""
SMARTIT_SLAVE_DB_FILESYNC_JAVA_MIN_HEAP_SIZE=""
SMARTIT_SLAVE_DB_FILESYNC_JAVA_MAX_HEAP_SIZE=""
SMARTIT_SLAVE_NON_HEAP_SIZE=""


SMARTIT_SLAVE_MEMORY_REQUEST="7Gi"
SMARTIT_SLAVE_CPU_REQUEST="100m"
SMARTIT_SLAVE_MEMORY_LIMIT="8Gi"
SMARTIT_SLAVE_CPU_LIMIT="6"
SMARTIT_SLAVE_VOLUME_MOUNT_ENABLED="true"
SMARTIT_SLAVE_VOLUME_ENABLED="true"

## Logzipper ##
SMARTIT_SLAVE_LOGZIPPER_ENABLED="false"





###################################
#### SMARTREPORTING PARAMETERS ####
###################################

###--------------------- SMARTREPORTING DEPLOYMENT PARAMETERS ---------------------###
SMARTREPORTING_REPLICA_COUNT="0"
SMARTREPORTING_JAVA_MIN_HEAP_SIZE="-Xms8192m"
SMARTREPORTING_JAVA_MAX_HEAP_SIZE="-Xmx8192m"


## Resources ##
SMARTREPORTING_MEMORY_REQUEST="9Gi"
SMARTREPORTING_CPU_REQUEST="100m"
SMARTREPORTING_MEMORY_LIMIT="10Gi"
SMARTREPORTING_CPU_LIMIT="4"



## Logzipper ##
SMARTREPORTING_LOGZIPPER_ENABLED="false"



####################
#### TSOMPLUGIN ####
####################
TSOMPLUGIN_REPLICA_COUNT="1"
TSOMPLUGIN_CUSTOM_PLUGIN_JVM_JAVA_HEAP_SIZE_MAX="-Xmx256m"

## Resources ##
TSOMPLUGIN_MEMORY_REQUEST="0.5Gi"
TSOMPLUGIN_CPU_REQUEST="1"
TSOMPLUGIN_MEMORY_LIMIT="1Gi"
TSOMPLUGIN_CPU_LIMIT="2"

## Logzipper ##
TSOMPLUGIN_PLUGIN_LOGZIPPER_ENABLED="false"

## volumeMounts ##
TSOMPLUGIN_VOLUME_MOUNT_ENABLED="true"

## volumes ##
TSOMPLUGIN_VOLUME_ENABLED="true"


######################
#### ATRIUMWEBSVC ####
######################
ATWS_REPLICA_COUNT="2"

## Resources ##
ATWS_MEMORY_REQUEST="2048Mi"
ATWS_CPU_REQUEST="100m"
ATWS_MEMORY_LIMIT="2356Mi"
ATWS_CPU_LIMIT="8"

## Logzipper ##
ATWS_LOGZIPPER_ENABLED="false"

## volumeMounts ##
ATWS_VOLUME_MOUNT_ENABLED="true"

## volumes ##
ATWS_VOLUME_ENABLED="true"

###########################
#### VIRTUALCHATSERVER ####
###########################

## Resources ##
VIRTUALCHATSERVER_MEMORY_REQUEST="2048Mi"
VIRTUALCHATSERVER_CPU_REQUEST="100m"
VIRTUALCHATSERVER_MEMORY_LIMIT="2356Mi"
VIRTUALCHATSERVER_CPU_LIMIT="2"

## Logzipper ##
VIRTUALCHATSERVER_LOGZIPPER_ENABLED="true"

## volumeMounts ##
VIRTUALCHATSERVER_VOLUME_MOUNT_ENABLED="true"

## volumes ##
VIRTUALCHATSERVER_VOLUME_ENABLED="true"

###########################
#### VIRTUALCHATPLUGIN ####
###########################
VIRTUALCHATPLUGIN_REPLICA_COUNT=2
VIRTUALCHATPLUGIN_CUSTOM_PLUGIN_JAVA_MIN_HEAP_SIZE="-Xms256m"
VIRTUALCHATPLUGIN_CUSTOM_PLUGIN_JAVA_MAX_HEAP_SIZE="-Xmx256m"

## Resources ##
VIRTUALCHATPLUGIN_MEMORY_REQUEST="1Gi"
VIRTUALCHATPLUGIN_CPU_REQUEST="100m"
VIRTUALCHATPLUGIN_MEMORY_LIMIT="1.5Gi"
VIRTUALCHATPLUGIN_CPU_LIMIT="2"

## Logzipper ##
VIRTUALCHATPLUGIN_LOGZIPPER_ENABLED="false"

## volumeMounts ##
VIRTUALCHATPLUGIN_VOLUME_MOUNT_ENABLED="true"

## volumes ##
VIRTUALCHATPLUGIN_VOLUME_ENABLED="true"

#####################
#### DRIFTPLUGIN ####
#####################

DRIFTPLUGIN_REPLICA_COUNT="1"
DRIFTPLUGIN_JAVA_MAX_HEAP_SIZE=""
DRIFTPLUGIN_JAVA_MIN_HEAP_SIZE=""

## RESOURCES ##
DRIFTPLUGIN_MEMORY_REQUEST=""
DRIFTPLUGIN_CPU_REQUEST=""
DRIFTPLUGIN_MEMORY_LIMIT=""
DRIFTPLUGIN_CPU_LIMIT=""

## volumeMounts ##
DRIFTPLUGIN_VOLUME_MOUNT_ENABLED="true"

## volumes ##
DRIFTPLUGIN_VOLUME_ENABLED="true"

##################
#### OPENFIRE ####
##################

## RESOURCES ##
OPENFIRE_MEMORY_REQUEST="2Gi"
OPENFIRE_CPU_REQUEST="100m"
OPENFIRE_MEMORY_LIMIT="3Gi"
OPENFIRE_CPU_LIMIT="1"

## volumeMounts ##
OPENFIRE_VOLUME_MOUNT_ENABLED="true"

## volumes ##
OPENFIRE_VOLUME_ENABLED="true"


##############
#### SCCM ####
##############

SCCM_INTEGRATION_TYPE="SCCM"
SCCM_INTEGRATION_SERVER_DB_TYPE=""
SCCM_INTEGRATION_SERVER_DB_PORT=""
SCCM_INTEGRATION_DB_SERVER_NAME=""
SCCM_INTEGRATION_DB_USER_NAME=""
SCCM_INTEGRATION_DB_NAME=""
SCCM_INTEGRATION_SERVER_DB_INSTANCE=""
SCCM_INTEGRATION_SERVER_DB_USER_PASSWORD=""
SCCM_INTEGRATION_AR_SERVER_NAME=""
SCCM_INTEGRATION_AR_SERVER_PORT="46262"
SCCM_INTEGRATION_AR_USER_NAME="Demo"
SCCM_INTEGRATION_AR_SERVER_RPC_PORT="0"



#############
#### BCM ####
#############

BCM_INTEGRATION_TYPE="BCM"
BCM_INTEGRATION_SERVER_DB_TYPE=""
BCM_INTEGRATION_SERVER_DB_PORT=""
BCM_INTEGRATION_DB_SERVER_NAME=""
BCM_INTEGRATION_DB_USER_NAME=""
BCM_INTEGRATION_DB_NAME=""
BCM_INTEGRATION_SERVER_DB_INSTANCE=""
BCM_INTEGRATION_SERVER_DB_USER_PASSWORD=""
BCM_INTEGRATION_AR_SERVER_NAME=""
BCM_INTEGRATION_AR_SERVER_PORT="46262"
BCM_INTEGRATION_AR_SERVER_RPC_PORT="0"
BCM_INTEGRATION_AR_USER_NAME="Demo"

#################
#### GRAFANA ####
#################
GRAFANA_REPLICA_COUNT=1

#################
#### LOCALES ####
#################

# Comma separated list of locales to install
# If kept empty will use default value. Supported locales are, "fr,de,it,es,ja,ko,zh_CN,pt_BR,he,ru,pl"
AR_LOCALE_TO_INSTALL=""


############################################# LICEENSE INFO #############################################

LICENSE_REMEDY_SERVICE_MANAGEMENT_SUITE_CONCURRENT_USER="LICENSE_SERVICE_MANAGEMENT_SUITE_CONCURRENT_USER"
LICENSE_REMEDY_SERVICE_MANAGEMENT_SUITE_USER="LICENSE_SERVICE_MANAGEMENT_SUITE_USER"
LICENSE_REMEDY_SERVICE_DESK_CONCURRENT_USER="LICENSE_SERVICE_DESK_CONCURRENT_USER"
LICENSE_REMEDY_SERVICE_DESK_USER="LICENSE_SERVICE_DESK_USER"
LICENSE_REMEDY_SERVICE_OPTIMIZATION_CONCURRENT_USER="LICENSE_SERVICE_OPTIMIZATION_CONCURRENT_USER"
LICENSE_REMEDY_SERVICE_OPTIMIZATION_USER="LICENSE_SERVICE_OPTIMIZATION_USER"


####################
#### TEST SUITE ####
####################

## FTP DETAILS ##
FTPSERVERNAME=""
FTPPORT=""
FTPUSERNAME=""
FTPPASSWORD=""
FTPRESULTFOLDER=""


####################
#### MAILBOX CONFIG ####
####################
SMTP_HOSTNAME=""
MAILBOX_NAME=""
MAILBOX_PASSWORD=""


######################################
####  PLATFORM TENANT PARAMETERS  ####
######################################
## Controller ##
PLATFORM_TENANT_CREATE="true"
TENANT_ID="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}"
TENANT_NAME="${CUSTOMER_SERVICE_NAME}"
TENANT_DOMAIN="${TENANT_DOMAIN}"
TENANT_HOST_NAME="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}"
HELIX_PLATFORM_NAMED_LIC="10"

######################################
####  PLATFORM WEBAPI PARAMETERS  ####
######################################
## Controller ##
WEBAPI_CONN_CREATE="HELIX_ITSM_INSIGHT"
#web api connection name should be unique in the system, default value is assigned below.
WEBAPI_CONNECTION_NAME="PLATFORM_RSSO_OAUTH_CLIENT"
WEBAPI_HOST_NAME="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-is.${CLUSTER_DOMAIN}"
WEBAPI_PORT="443"

####################
#### SMART APPS ####
####################

## Controllers ##
SMARTAPPS_BWF="HELIX_BWF"
SMARTAPPS_MCSM="HELIX_MCSM"
SMARTAPPS_ITSM_INSIGHTS="HELIX_ITSM_INSIGHT"
SMARTAPPS_CHATOPS="BLUEMIX_HELIX_COGNITIVE_CHATBOT_FLAG"
SMARTAPPS_DWP="HELIX_DWP_FLAG"
SMARTAPPS_CATALOG="HELIX_DWPA_FLAG"
SMARTAPPS_CATALOGLIB="HELIX_DWPA_FLAG"
SMARTAPPS_HDA_AUTOMATION="false"
SMARTAPPS_TELCO="${SMARTAPPS_TELCO}"
SMARTAPPS_CSM="${SMARTAPPS_CSM}"
SMARTAPPS_FAS="${SMARTAPPS_FAS}"
BWF_INCOMING_MAIL_BOX_NAME=""
BWF_MAILBOX_PASSWORD=""

SMARTAPPS_LICENSE_BWF="HELIX_BWF"
SMARTAPPS_LICENSE_TELCO="${SMARTAPPS_TELCO}"
SMARTAPPS_LICENSE_MCSM="HELIX_MCSM"
SMARTAPPS_LICENSE_ITSM_INSIGHTS="HELIX_ITSM_INSIGHT"

#Controller to decide if we would like to license the smart bundles. E.g. true/false.
SMARTAPPS_LICENSE="true"
#This is list of smartapps bundle. E.g. BWF bundles are SMARTAPPS_BUNDLES="com.bmc.dsm.task-lib com.bmc.dsm.ticketing-lib com.bmc.dsm.notification-lib com.bmc.dsm.flowsets-lib com.bmc.dsm.social-lib com.bmc.dsm.search-lib com.bmc.dsm.attachment-service-lib com.bmc.dsm.knowledge com.bmc.dsm.bwfa com.bmc.dsm.slm-lib com.bmc.dsm.shared-components-lib com.bmc.dsm.shared-services-lib com.bmc.dsm.case-lib com.bmc.dsm.cognitive-lib com.bmc.dsm.email-lib". You can have all application bundles in the same go.
SMARTAPPS_BUNDLES="${BUNDLES_LIST}"
SMARTAPPS_ADMIN=""
SMARTAPPS_PASSWORD=""

SMARTAPPS_HELM_REPO="http://zwl-gogs-1.onbmc.com:3000/core-remedy/containerization-smartapps-certified.git"
SMARTAPPS_HELM_VERSION="2022106.0.03.06"
SMARTAPPS_HELM_IMAGES_FILE="dtr.yaml"
SMARTAPPS_DEPLOYMENT_TYPE=""

#############
#### DWP ####
#############
DWP_PRE_DEPLOY="HELIX_DWP_FLAG"
DWP_TOMCAT_DEPLOY="HELIX_DWP_FLAG"
DWP_TOMCAT_CUSTOM_BRANDING_ENABLED="${DWP_TOMCAT_CUSTOM_BRANDING_ENABLED}"
DWP_TOMCAT_SAAS="false"
DWP_TOMCAT_SMTP_ENABLED="false"
DWP_TOMCAT_SMTP_HOST=""
DWP_TOMCAT_SMTP_PORT=""
DWP_TOMCAT_SMTP_ACCOUNT=""
DWP_TOMCAT_SMTP_PWD=""
DWP_TOMCAT_SSO_MSP_DEPLOYMENT="false"
DWP_TOMCAT_SSO_MSP_SHOW_ENTRY_PAGE="false"
DWP_TOMCAT_SESSION_TIMEOUT_MIN="30"
DWP_TOMCAT_SHOW_HELIX_LOGO="true"
#DWP_TOMCAT_SBE_IMAGE_PROXY_ENABLED="true"
DWP_TOMCAT_SBE_SEARCH_FTS_ENABLED="true"
DWP_TOMCAT_SAMESITE_COOKIE_ATTRIBUTE=""
DWP_TOMCAT_RSSO_ENABLED="true"
DWP_TOMCAT_RSSO_EXTERNAL_URL="${RSSO_URL}"
#DWP_TOMCAT_RSSO_EXTERNAL_URL="https://${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}-rsso.${CLUSTER_DOMAIN}/rsso"
DWP_TOMCAT_RSSO_SERVICE_URL="${RSSO_URL}"
#DWP_TOMCAT_RSSO_SERVICE_URL="https://${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}-rsso.${CLUSTER_DOMAIN}/rsso"
DWP_TOMCAT_RSSO_AGENT_ID="${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}"

DWP_TOMCAT_EFK_ENABLED="false"
DWP_TOMCAT_ES_HOST=""
DWP_TOMCAT_ES_PORT=""

DWP_TOMCAT_EXTERNAL_CERTS_ENABLED="true"
DWP_TOMCAT_HOST_FILE_ENABLED=""
DWP_TOMCAT_HOSTNAME_ALIASES=""

#DWP_TOMCAT_HOSTNAME_ALIAS_1=""
#DWP_TOMCAT_HOSTNAME_ALIAS_2=""
#DWP_TOMCAT_HOSTNAME_ALIAS_IP=""

DWP_TOMCAT_FLUENTBIT_ENABLED="false"
DWP_TOMCAT_FLUENTBIT_REGISTRY=""
DWP_TOMCAT_FLUENTBIT_IMAGE=""
DWP_TOMCAT_FLUENTBIT_TAG=""
DWP_TOMCAT_FLUENTBIT_TAG_FORMAT1=""
DWP_TOMCAT_FLUENTBIT_TAG_FORMAT2=""
DWP_TOMCAT_FLUENTBIT_RESOURCE_ENABLED="false"
DWP_URL_ALIAS="${DWP_URL_ALIAS}"
DWP_TOMCAT_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-dwp.${CLUSTER_DOMAIN}"
DWP_TOMCAT_INGRESS_ENABLED="${ingress_enabled}"
DWP_TOMCAT_ROUTE_ENABLED="${route_enabled}"
DWP_TOMCAT_MIN_HEAP_SIZE="-Xms6144m"
DWP_TOMCAT_MAX_HEAP_SIZE="-Xmx6144m"
DWP_TOMCAT_SLAVE_REPLICAS="1"
DWP_TOMCAT_MASTER_REPLICAS="1"
DWP_CONFIG_DEPLOY="true"

## RESOURCES ##
DWP_TOMCAT_MEMORY_REQUEST="2048Mi"
DWP_TOMCAT_CPU_REQUEST="100m"
DWP_TOMCAT_MEMORY_LIMIT="8192Mi"
DWP_TOMCAT_CPU_LIMIT="1.5"

DWP_CONFIG_PRIMARY_ORG_NAME=""
DWP_CONFIG_AR_HOST="platform-user-ext"
DWP_CONFIG_AR_PORT="46262"
DWP_CONFIG_AR_PASSWORD="${AR_SERVER_APP_SERVICE_PASSWORD}"
DWP_CONFIG_RUNMODE_VALUE="2169487"
DWP_CONFIG_ENABLE_ADVANCED_TRIAL_PERIOD="false"
DWP_SOURCE_RUNMODE="2169487"

DWP_CONFIG_CHAT_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-vchat.${CLUSTER_DOMAIN}"
DWP_CONFIG_MYITBACKEND_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-dwp.${CLUSTER_DOMAIN}/dwp"
DWP_CONFIG_SENDER_EMAIL=""
DWP_CONFIG_EXTERNAL_HOST_DOMAINS=""
DWP_CONFIG_ENABLE_FEATURE_VIRTUALCHAT="true"
DWP_CONFIG_ENABLE_FEATURE_SBE="HELIX_DWPA_FLAG"
DWP_CONFIG_SBE_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-dwpcatalog.${CLUSTER_DOMAIN}/api/myit-sb"
DWP_CONFIG_SBE_SYSTEM_USER="hannah_admin"
DWP_CONFIG_SBE_SYSTEM_USER_PASSWORD=""

DWP_CONFIG_SUBTENANT_USER_PASSWORD=""
DWP_CONFIG_TENANT_ADMIN_FIRST_NAME="Hannah"
DWP_CONFIG_TENANT_ADMIN_LAST_NAME="Admin"
DWP_CONFIG_TENANT_ADMIN_PASSWORD="${DWP_CONFIG_TENANT_ADMIN_PASSWORD}"
DWP_CONFIG_TENANT_ADMIN_USER="hannah_admin"

DWP_ITSM_PATCH_DEPLOY="HELIX_DWP_FLAG"
DWP_CONFIG_BWF_PROVIDER="false"

## Settings required to configure BWF pluggable provider
##Connection Timeout value should be in seconds
DWP_CONFIG_BWF_CONNECTION_TIMEOUT=""
## User must have Case Management Permission
DWP_CONFIG_BWF_SYSTEM_USER=""
DWP_CONFIG_BWF_SYSTEM_PASSWORD=""
DWP_CONFIG_BWF_TENANT_NAME=""

#comaround
DWP_CONFIGURE_COMAROUND_PROVIDER=""
DWP_CONFIG_COMAROUND_CONNECTION_TIMEOUT=""
DWP_CONFIG_COMAROUND_SYSTEM_USER=""
DWP_CONFIG_COMAROUND_SYSTEM_PASSWORD=""
DWP_CONFIG_COMAROUND_USE_LOCALE=""
DWP_CONFIG_COMAROUND_FB_RATING_CODE_MAPPING=""
DWP_CONFIG_COMAROUND_ARTICLE_SORTBY=""
DWP_CONFIG_COMAROUND_FB_APPLY_USER_EMAIL=""

#DWP External Url Settings
# Json {"tenantName":"ingress",...} format to create additional ingress for external tenant
DWP_EXTRA_TENANTS=''

BWF_DEPLOY_SAMPLE_CONTENT_PACK="false"
DWP_DEPLOY_SAMPLE_CONTENT_PACK="false"

#################
#### Catalog ####
#################
 
## Route ##
CATALOG_ROUTE_ENABLED="${route_enabled}"
CATALOG_ROUTE_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-dwpcatalog"
CATALOG_ROUTE_DOMAIN="${CLUSTER_DOMAIN}"
 
## INGRESS ##
CATALOG_INGRESS_ENABLED="${ingress_enabled}"
CATALOG_INGRESS_HOST="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-dwpcatalog"
CATALOG_INGRESS_DOMAIN="${CLUSTER_DOMAIN}"


CATALOG_D2P_PLUGIN_DEPLOY="HELIX_DWPA_FLAG"
CATALOG_ITSM_INTEGRATION_PLUGIN_DEPLOY="HELIX_DWPA_FLAG"

CATALOG_ITSM_INTEGRATION_PLUGIN_CPU_REQUEST="100m"
CATALOG_ITSM_INTEGRATION_PLUGIN_MEMORY_REQUEST="1Gi"
CATALOG_ITSM_INTEGRATION_PLUGIN_CPU_LIMIT="2"
CATALOG_ITSM_INTEGRATION_PLUGIN_MEMORY_LIMIT="1Gi"
CATALOG_ITSM_INTEGRATION_PLUGIN_MIN_HEAP_SIZE="-Xms256m"
CATALOG_ITSM_INTEGRATION_PLUGIN_MAX_HEAP_SIZE="-Xmx1024m"
CATALOG_ITSM_INTEGRATION_PLUGIN_REPLICAS=2

## volumeMounts ##
CATALOG_ITSM_INTEGRATION_PLUGIN_VOLUME_MOUNT_ENABLED="true"

## volumes ##
CATALOG_ITSM_INTEGRATION_PLUGIN_VOLUME_ENABLED="true"

#CATALOG CONFIGURATION
CATALOG_CONFIG_DEPLOY="HELIX_DWPA_FLAG"
CATALOG_CONFIG_USERID_GRANT_DWPC_ROLE="hannah_admin"
CATALOG_CONFIG_APPROVAL_REMOTE_HOST="platform-user-ext"
CATALOG_CONFIG_DWPC_ADMIN="hannah_admin"
CATALOG_CONFIG_DWPC_ADMIN_PASSWORD=""
CATALOG_CONFIG_CHATBOT_URL=""
CATALOG_CONFIG_PLATFORM_CONNECTOR_URL="https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-is.${CLUSTER_DOMAIN}"
#CATALOG_CONFIG_PLATFORM_CONNECTOR_USER="${DWP_CONFIG_TENANT_ADMIN_USER}"
CATALOG_CONFIG_PLATFORM_CONNECTOR_USER="hannah_admin"
CATALOG_CONFIG_PLATFORM_CONNECTOR_PASSWORD="${DWP_CONFIG_TENANT_ADMIN_PASSWORD}"
#CATALOG_CONFIG_ENABLE_MSP="${MIDTIER_MSP_DEPLOYMENT}"
CATALOG_CONFIG_ENABLE_MSP=""

CATALOG_DATA_UPGRADE_DEPLOY="false"

###################################################################
#### IBM Bluemix Watson service provisioning and configuration ####
###################################################################
BLUEMIX_HELIX_COGNITIVE_REGION="US_SOUTH"
#CHATBOT
BLUEMIX_HELIX_COGNITIVE_CHATBOT="BLUEMIX_HELIX_COGNITIVE_CHATBOT_FLAG"
BLUEMIX_HELIX_COGNITIVE_CHATBOT_PLAN="BLUEMIX_HELIX_COGNITIVE_CHATBOT_PLAN_FLAG"
BLUEMIX_HELIX_COGNITIVE_CHATBOT_REGION=""
BLUEMIX_HELIX_COGNITIVE_CHATBOT_SINGLE_WATSON_INSTANCE="true"
BLUEMIX_HELIX_COGNITIVE_CHATBOT_TELEMETRY_CAPACITY="CHATBOT_CUSTOMER_CAPACITY_FLAG"
BLUEMIX_HELIX_COGNITIVE_CONFIGURE_OWN_PROVIDER="false"

#Cognitive Automation includes NLC TONEANALYZER AND SUMMARIZATION
BLUEMIX_HELIX_COGNITIVE_AUTOMATION_TELEMETRY_CAPACITY="COGNITIVE_AUTOMATION_CAPACITY_FLAG"


#NLC
BLUEMIX_HELIX_COGNITIVE_AUTOMATION_NLC="BLUEMIX_HELIX_COGNITIVE_AUTOMATION_FLAG"
BLUEMIX_HELIX_COGNITIVE_AUTOMATION_NLC_PLAN="BLUEMIX_HELIX_COGNITIVE_AUTOMATION_NLC_PLAN_FLAG"
BLUEMIX_HELIX_COGNITIVE_AUTOMATION_NLC_REGION=""
BLUEMIX_HELIX_COGNITIVE_AUTOMATION_NLC_SINGLE_WATSON_INSTANCE="true"

#TONEANALYZER
BLUEMIX_HELIX_COGNITIVE_AUTOMATION_TONEANALYZER="BLUEMIX_HELIX_COGNITIVE_AUTOMATION_FLAG"
BLUEMIX_HELIX_COGNITIVE_AUTOMATION_TONEANALYZER_PLAN="BLUEMIX_HELIX_COGNITIVE_AUTOMATION_TONEANALYZER_PLAN_FLAG"
BLUEMIX_HELIX_COGNITIVE_AUTOMATION_TONEANALYZER_REGION=""
BLUEMIX_HELIX_COGNITIVE_AUTOMATION_TONEANALYZER_SINGLE_WATSON_INSTANCE="false"

#SEARCH
BLUEMIX_HELIX_COGNITIVE_SEARCH="BLUEMIX_HELIX_COGNITIVE_SEARCH_FLAG"
BLUEMIX_HELIX_COGNITIVE_SEARCH_PLAN="BLUEMIX_HELIX_COGNITIVE_SEARCH_PLAN_FLAG"
BLUEMIX_HELIX_COGNITIVE_SEARCH_REGION=""
BLUEMIX_HELIX_COGNITIVE_SEARCH_SINGLE_WATSON_INSTANCE="true"

# Need to set some value here, not being used
BLUEMIX_HELIX_COGNITIVE_SEARCH_TELEMETRY_CAPACITY="1000" 


BLUEMIX_ENV="${BLUEMIX_ENV}"
BLUEMIX_TENANT_USER_EMAIL_ID=""
BLUEMIX_NOTIFY_EMAIL_ADDRESSES=""
BLUEMIX_EXTERNAL_USERS_TO_BE_ADDED_AS_MANAGERS=""
#IBM user id and api key
BLUEMIX_USERID=""
BLUEMIX_API_KEY=""
BLUEMIX_ORG_NAME=""

BLUEMIX_CHATBOT_NAMES="BMC Chatbot, Helix Chatops, BMC ITOps Chatbot"
BLUEMIX_CHAT_BUNDLE_NAMES="com.bmc.dsm.chatbot, com.bmc.bsm.chatops, com.bmc.dsm.chatbot"
BLUEMIX_CHAT_WORKSPACE_TEMPLATE_JSON_FILEPATHS="/opt/bmc/ars/bluemix/chatbot-workspace.json,/opt/bmc/ars/bluemix/chatops-smartit-workspace.json,/opt/bmc/ars/bluemix/itops-chatbot-workspace.json"
BLUEMIX_TELEMETRY_THRESHOLDS="80,90,100"
BLUEMIX_MAXPREMIUM_RESOURCE_INSTANCES_THRESHOLD="30"
BLUEMIX_ALLOWED_PREMIUM_SERVICES="CONVERSATION"
BLUEMIX_ALLOWED_PREMIUM_REGIONS="eu-de,us-south"
BLUEMIX_PREMIUM_RESOURCEGROUP_NAME="Premium Environment Resource Group"
BLUEMIX_VALID_PREMIUM_RESOURCEGROUPS_EU_DE="Premium Environment Resource Group, Frankfurt Premium WA Services2, Frankfurt Premium WA Services3"
BLUEMIX_VALID_PREMIUM_RESOURCEGROUPS_US_SOUTH="US South Premium WA Services"
BLUEMIX_DISCOVERY_ENVIRONMENT_SIZE="COGNITIVE_SEARCH_CAPACITY_FLAG"

#BLUEMIX_AZURE
BLUEMIX_AZURE_API_MANAGEMENT_SUBSCRIPTION_ID=""
BLUEMIX_AZURE_API_MANAGEMENT_USER_EMAIL=""
BLUEMIX_AZURE_API_MANAGEMENT_USER_FIRSTNAME=""
BLUEMIX_AZURE_API_MANAGEMENT_USER_LASTNAME=""
BLUEMIX_AZURE_API_MANAGEMENT_USER_SUBSCRIPTION=""
BLUEMIX_AZURE_API_MANAGEMENT_USER_SUBSCRIPTION_DISPLAYNAME=""
BLUEMIX_AZURE_API_MANAGEMENT_USER_SUBSCRIPTION_PRODUCTNAME=""
BLUEMIX_AZURE_APP_REGISTRATION_TENANT_ID=""
BLUEMIX_AZURE_TOKEN_CLIENT_ID=""
BLUEMIX_AZURE_TOKEN_CLIENT_SECRET=""

#BLUEMIX_COMAROUND
BLUEMIX_COMAROUND_CUSTOMER_JSON=""
BLUEMIX_COMAROUND_FRAME_URL=""
BLUEMIX_COMAROUND_IDENTITY_CLIENT_ID=""
BLUEMIX_COMAROUND_IDENTITY_CLIENT_SECRET=""
BLUEMIX_COMAROUND_IDENTITY_HOST=""
BLUEMIX_COMAROUND_MAIN_URL=""
BLUEMIX_COMAROUND_SERVER_URL=""
BLUEMIX_COMAROUND_SUBSCRIPTION_KEY=""
BLUEMIX_COMAROUND_SYS_ADMIN_PASSWORD=""
BLUEMIX_COMAROUND_SYS_ADMIN_USER=""
BLUEMIX_HELIX_HKM=""
BLUEMIX_SAAS_ADMIN_USER_ID=""
###################################################################
#### Chatbot Configuration for DWP DWPC VC and Cloud Cost      ####
###################################################################
## Controller ##
CHATBOT_CONFIG="BLUEMIX_HELIX_COGNITIVE_CHATBOT_FLAG"
CHATBOT_CONFIG_DWP_URL='https://${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-dwp.${CLUSTER_DOMAIN}/dwp/app'
CHATBOT_CONFIG_DWP_RESOURCE_SERVER="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-dwp.${CLUSTER_DOMAIN}"
CHATBOT_CONFIG_CLOUD_COST_RESOURCE_SERVER=""
CHATBOT_CONFIG_CLOUD_COST_API_ENDPOINT=""
CHATBOT_CONFIG_CLOUD_COST_DASHBOARD_URL=""

CHATOPS_RSSO_API_AUTH_ENDPOINT="${RSSO_URL}"
CHATOPS_RSSO_CLIENT_REDIRECT_URL="${RSSO_URL}"
#CHATOPS_RSSO_API_AUTH_ENDPOINT="https://${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}-rsso.${CLUSTER_DOMAIN}/rsso"
#CHATOPS_RSSO_CLIENT_REDIRECT_URL="https://${CUSTOMER_SERVICE_NAME}-${ENVIRONMENT}-rsso.${CLUSTER_DOMAIN}/rsso"
CHATOPS_SKIP_ISUITE_CONNECTION_CONFIGURATION="false"
CHATOPS_SKIP_RSSO_CONFIGURATION="false"
CHATOPS_RSSO_CLIENT_NAME="${CUSTOMER_SERVICE_NAME}${ENVIRONMENT_URL}-com.bmc.chatops"

COGNITIVE_SUMMARIZATION_SERVICE_CONFIG="false"
COGNITIVE_SUMMARIZATION_SERVICE_URL="SUMMARIZATION_SERVICE_URL_FLAG"
COGNITIVE_SUMMARIZATION_SERVICE_USER="SUMMARIZATION_SERVICE_USER_FLAG"
COGNITIVE_SUMMARIZATION_SERVICE_USER_PASSWORD="SUMMARIZATION_SERVICE_USER_PASSWORD_FLAG"

DATA_STREAMING_BROKER_LIST=""
DATA_STREAMING_IS_NAME=""
DATA_STREAMING_SERVICE_URL=""
DATA_STREAMING_SUPER_USER=""
DATA_STREAMING_SUPER_USER_PASSWORD=""

RSSO_TENANT_HOST=""
TELEMETRY_ADMIN_USER=""
TELEMETRY_ADMIN_USER_PASSWORD=""
TELEMETRY_APP_NAME=""
TELEMETRY_REGISTRY=""
TELEMETRY_SERVICE_URL=""

#Passwords
BAKEDUSER_HANNAH_ADMIN_PASSWORD=""
BAKEDUSER_SRADMIN_PASSWORD=""
BAKEDUSER_ACTIVATIONUSER_PASSWORD=""

# Integration Service Authentication configuration in Innovation Studio
INTEGRATION_SERVICE_REGISTRY="false"
INTEGRATION_SERVICE_URL=""
INTEGRATION_SERVICE_USERNAME=""
INTEGRATION_SERVICE_PASSWORD=""

##################
##### CLAMAV #####
##################
CLAMAV_REPLICA_COUNT="1"
CLAMAV_MEMORY_REQUEST=""
CLAMAV_CPU_REQUEST=""
CLAMAV_MEMORY_LIMIT=""
CLAMAV_CPU_LIMIT=""

###################
#### STALEDATA ####
###################
STALEDATA_REPLICA_COUNT=""
STALEDATA_JAVA_MAX_HEAP_SIZE=""
STALEDATA_JAVA_MIN_HEAP_SIZE=""

## RESOURCES ##
STALEDATA_MEMORY_REQUEST=""
STALEDATA_CPU_REQUEST=""
STALEDATA_MEMORY_LIMIT=""
STALEDATA_CPU_LIMIT=""

## volumeMounts ##
STALEDATA_VOLUME_MOUNT_ENABLED="true"

## volumes ##
STALEDATA_VOLUME_ENABLED="true"